import os

TOKEN = os.getenv("DISCORD_TOKEN", "YOUR_TOKEN_HERE")
CLIENT_ID = os.getenv("DISCORD_CLIENT_ID", "YOUR_CLIENT_ID_HERE")
CLIENT_SECRET = os.getenv("DISCORD_CLIENT_SECRET", "YOUR_CLIENT_SECRET_HERE")
GUILD_ID = None
